export const PATH = {
    REGISTRATION: '/registration',
    LOGIN: '/login',
    ERROR: '/404',
    EDIT_PROFILE:'/edit',
    PROFILE: '/',
    MAIN: '/main',
    // PACK_LIST: '/main/pack-list',
    EDIT_PACK: '/main/pack-list/edit-pack',
    TEST: '/test',
    CHANGE_PASSWORD: '/change-pass/:token',
    PASSWORD_RECOVERY: '/pass-recovery',
    CARDS: '/packs/:id',
    PACKS: '/main/packs',
}